service: 
  name: skycave-message-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

functions:
  createMessage:
    handler: ./src/handlers/createMessage.handler
    events:
      - http:
          method: POST
          path: /message/{position}
  
  getInfo:
    handler: ./src/handlers/info.handler
    events:
      - http:
          method: GET
          path: /info
  