MessageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MessageTable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: position
            AttributeType: S
          - AttributeName: creatorTimeStampISO8601
            AttributeType: S
          - AttributeName: positionIndex
            AttributeType: 'N'
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: positionAndCreationTime
            KeySchema:
              - AttributeName: position
                KeyType: HASH
              - AttributeName: creatorTimeStampISO8601
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: positionIndex
            KeySchema:
              - AttributeName: position
                KeyType: HASH
              - AttributeName: positionIndex
                KeyType: RANGE
            Projection:
              ProjectionType: ALL


